version: '2'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    image: arorashivang97/spe-project:app
    volumes:
      - ./home/sem8/spe/elk/logs:/code/app/log
    ports:
      - '1337:1337'
      - '4999:4999'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: arorashivang97/spe-project:app_mongo
    ports:
      - '27017:27017'
